package com.pojos;
// Generated 01.Ara.2014 13:53:21 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Aile generated by hbm2java
 */
public class Aile  implements java.io.Serializable {


     private int aileid;
     private String soyad;
     private String il;
     private Set<Akraba> akrabas = new HashSet<Akraba>(0);

    public Aile() {
    }

	
    public Aile(int aileid) {
        this.aileid = aileid;
    }
    public Aile(int aileid, String soyad, String il, Set<Akraba> akrabas) {
       this.aileid = aileid;
       this.soyad = soyad;
       this.il = il;
       this.akrabas = akrabas;
    }
   
    public int getAileid() {
        return this.aileid;
    }
    
    public void setAileid(int aileid) {
        this.aileid = aileid;
    }
    public String getSoyad() {
        return this.soyad;
    }
    
    public void setSoyad(String soyad) {
        this.soyad = soyad;
    }
    public String getIl() {
        return this.il;
    }
    
    public void setIl(String il) {
        this.il = il;
    }
    public Set<Akraba> getAkrabas() {
        return this.akrabas;
    }
    
    public void setAkrabas(Set<Akraba> akrabas) {
        this.akrabas = akrabas;
    }




}


