package com.pojos;
// Generated 01.Ara.2014 13:53:21 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Birey generated by hbm2java
 */
public class Birey  implements java.io.Serializable {


     private String tcno;
     private Adres adres;
     private String ad;
     private String soyad;
     private String dyeri;
     private Date dtarih;
     private String tel;
     private String mail;
     private String sifre;
     private String tema;
     private Set<Recete> recetes = new HashSet<Recete>(0);
     private Set<Khastalik> khastaliks = new HashSet<Khastalik>(0);
     private Set<Akraba> akrabas = new HashSet<Akraba>(0);

    public Birey() {
    }

	
    public Birey(String tcno) {
        this.tcno = tcno;
    }
    public Birey(String tcno, Adres adres, String ad, String soyad, String dyeri, Date dtarih, String tel, String mail, String sifre, String tema, Set<Recete> recetes, Set<Khastalik> khastaliks, Set<Akraba> akrabas) {
       this.tcno = tcno;
       this.adres = adres;
       this.ad = ad;
       this.soyad = soyad;
       this.dyeri = dyeri;
       this.dtarih = dtarih;
       this.tel = tel;
       this.mail = mail;
       this.sifre = sifre;
       this.tema = tema;
       this.recetes = recetes;
       this.khastaliks = khastaliks;
       this.akrabas = akrabas;
    }
   
    public String getTcno() {
        return this.tcno;
    }
    
    public void setTcno(String tcno) {
        this.tcno = tcno;
    }
    public Adres getAdres() {
        return this.adres;
    }
    
    public void setAdres(Adres adres) {
        this.adres = adres;
    }
    public String getAd() {
        return this.ad;
    }
    
    public void setAd(String ad) {
        this.ad = ad;
    }
    public String getSoyad() {
        return this.soyad;
    }
    
    public void setSoyad(String soyad) {
        this.soyad = soyad;
    }
    public String getDyeri() {
        return this.dyeri;
    }
    
    public void setDyeri(String dyeri) {
        this.dyeri = dyeri;
    }
    public Date getDtarih() {
        return this.dtarih;
    }
    
    public void setDtarih(Date dtarih) {
        this.dtarih = dtarih;
    }
    public String getTel() {
        return this.tel;
    }
    
    public void setTel(String tel) {
        this.tel = tel;
    }
    public String getMail() {
        return this.mail;
    }
    
    public void setMail(String mail) {
        this.mail = mail;
    }
    public String getSifre() {
        return this.sifre;
    }
    
    public void setSifre(String sifre) {
        this.sifre = sifre;
    }
    public String getTema() {
        return this.tema;
    }
    
    public void setTema(String tema) {
        this.tema = tema;
    }
    public Set<Recete> getRecetes() {
        return this.recetes;
    }
    
    public void setRecetes(Set<Recete> recetes) {
        this.recetes = recetes;
    }
    public Set<Khastalik> getKhastaliks() {
        return this.khastaliks;
    }
    
    public void setKhastaliks(Set<Khastalik> khastaliks) {
        this.khastaliks = khastaliks;
    }
    public Set<Akraba> getAkrabas() {
        return this.akrabas;
    }
    
    public void setAkrabas(Set<Akraba> akrabas) {
        this.akrabas = akrabas;
    }




}


