package com.pojos;
// Generated 01.Ara.2014 13:53:21 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Birim generated by hbm2java
 */
public class Birim  implements java.io.Serializable {


     private int bid;
     private String tanim;
     private Set<Doktor> doktors = new HashSet<Doktor>(0);
     private Set<Hbirim> hbirims = new HashSet<Hbirim>(0);

    public Birim() {
    }

	
    public Birim(int bid) {
        this.bid = bid;
    }
    public Birim(int bid, String tanim, Set<Doktor> doktors, Set<Hbirim> hbirims) {
       this.bid = bid;
       this.tanim = tanim;
       this.doktors = doktors;
       this.hbirims = hbirims;
    }
   
    public int getBid() {
        return this.bid;
    }
    
    public void setBid(int bid) {
        this.bid = bid;
    }
    public String getTanim() {
        return this.tanim;
    }
    
    public void setTanim(String tanim) {
        this.tanim = tanim;
    }
    public Set<Doktor> getDoktors() {
        return this.doktors;
    }
    
    public void setDoktors(Set<Doktor> doktors) {
        this.doktors = doktors;
    }
    public Set<Hbirim> getHbirims() {
        return this.hbirims;
    }
    
    public void setHbirims(Set<Hbirim> hbirims) {
        this.hbirims = hbirims;
    }




}


