package com.pojos;
// Generated 01.Ara.2014 13:53:21 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Doktor generated by hbm2java
 */
public class Doktor  implements java.io.Serializable {


     private String dtcno;
     private Birim birim;
     private Hastane hastane;
     private String ad;
     private String soyad;
     private String tel;
     private String mail;
     private Set<Recete> recetes = new HashSet<Recete>(0);

    public Doktor() {
    }

	
    public Doktor(String dtcno) {
        this.dtcno = dtcno;
    }
    public Doktor(String dtcno, Birim birim, Hastane hastane, String ad, String soyad, String tel, String mail, Set<Recete> recetes) {
       this.dtcno = dtcno;
       this.birim = birim;
       this.hastane = hastane;
       this.ad = ad;
       this.soyad = soyad;
       this.tel = tel;
       this.mail = mail;
       this.recetes = recetes;
    }
   
    public String getDtcno() {
        return this.dtcno;
    }
    
    public void setDtcno(String dtcno) {
        this.dtcno = dtcno;
    }
    public Birim getBirim() {
        return this.birim;
    }
    
    public void setBirim(Birim birim) {
        this.birim = birim;
    }
    public Hastane getHastane() {
        return this.hastane;
    }
    
    public void setHastane(Hastane hastane) {
        this.hastane = hastane;
    }
    public String getAd() {
        return this.ad;
    }
    
    public void setAd(String ad) {
        this.ad = ad;
    }
    public String getSoyad() {
        return this.soyad;
    }
    
    public void setSoyad(String soyad) {
        this.soyad = soyad;
    }
    public String getTel() {
        return this.tel;
    }
    
    public void setTel(String tel) {
        this.tel = tel;
    }
    public String getMail() {
        return this.mail;
    }
    
    public void setMail(String mail) {
        this.mail = mail;
    }
    public Set<Recete> getRecetes() {
        return this.recetes;
    }
    
    public void setRecetes(Set<Recete> recetes) {
        this.recetes = recetes;
    }




}


