package com.pojos;
// Generated 01.Ara.2014 13:53:21 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Doz generated by hbm2java
 */
public class Doz  implements java.io.Serializable {


     private int dozid;
     private String tanim;
     private Set<IlacBilgi> ilacBilgis = new HashSet<IlacBilgi>(0);

    public Doz() {
    }

	
    public Doz(int dozid) {
        this.dozid = dozid;
    }
    public Doz(int dozid, String tanim, Set<IlacBilgi> ilacBilgis) {
       this.dozid = dozid;
       this.tanim = tanim;
       this.ilacBilgis = ilacBilgis;
    }
   
    public int getDozid() {
        return this.dozid;
    }
    
    public void setDozid(int dozid) {
        this.dozid = dozid;
    }
    public String getTanim() {
        return this.tanim;
    }
    
    public void setTanim(String tanim) {
        this.tanim = tanim;
    }
    public Set<IlacBilgi> getIlacBilgis() {
        return this.ilacBilgis;
    }
    
    public void setIlacBilgis(Set<IlacBilgi> ilacBilgis) {
        this.ilacBilgis = ilacBilgis;
    }




}


