package com.pojos;
// Generated 01.Ara.2014 13:53:21 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Durum generated by hbm2java
 */
public class Durum  implements java.io.Serializable {


     private int did;
     private String tanim;
     private Set<Akraba> akrabas = new HashSet<Akraba>(0);

    public Durum() {
    }

	
    public Durum(int did) {
        this.did = did;
    }
    public Durum(int did, String tanim, Set<Akraba> akrabas) {
       this.did = did;
       this.tanim = tanim;
       this.akrabas = akrabas;
    }
   
    public int getDid() {
        return this.did;
    }
    
    public void setDid(int did) {
        this.did = did;
    }
    public String getTanim() {
        return this.tanim;
    }
    
    public void setTanim(String tanim) {
        this.tanim = tanim;
    }
    public Set<Akraba> getAkrabas() {
        return this.akrabas;
    }
    
    public void setAkrabas(Set<Akraba> akrabas) {
        this.akrabas = akrabas;
    }




}


