package com.pojos;
// Generated 01.Ara.2014 13:53:21 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Eczane generated by hbm2java
 */
public class Eczane  implements java.io.Serializable {


     private int eid;
     private String ad;
     private String il;
     private String ilce;
     private String konum;
     private String mahalle;
     private String tel;
     private Set<Recete> recetes = new HashSet<Recete>(0);

    public Eczane() {
    }

	
    public Eczane(int eid) {
        this.eid = eid;
    }
    public Eczane(int eid, String ad, String il, String ilce, String konum, String mahalle, String tel, Set<Recete> recetes) {
       this.eid = eid;
       this.ad = ad;
       this.il = il;
       this.ilce = ilce;
       this.konum = konum;
       this.mahalle = mahalle;
       this.tel = tel;
       this.recetes = recetes;
    }
   
    public int getEid() {
        return this.eid;
    }
    
    public void setEid(int eid) {
        this.eid = eid;
    }
    public String getAd() {
        return this.ad;
    }
    
    public void setAd(String ad) {
        this.ad = ad;
    }
    public String getIl() {
        return this.il;
    }
    
    public void setIl(String il) {
        this.il = il;
    }
    public String getIlce() {
        return this.ilce;
    }
    
    public void setIlce(String ilce) {
        this.ilce = ilce;
    }
    public String getKonum() {
        return this.konum;
    }
    
    public void setKonum(String konum) {
        this.konum = konum;
    }
    public String getMahalle() {
        return this.mahalle;
    }
    
    public void setMahalle(String mahalle) {
        this.mahalle = mahalle;
    }
    public String getTel() {
        return this.tel;
    }
    
    public void setTel(String tel) {
        this.tel = tel;
    }
    public Set<Recete> getRecetes() {
        return this.recetes;
    }
    
    public void setRecetes(Set<Recete> recetes) {
        this.recetes = recetes;
    }




}


