package com.pojos;
// Generated 01.Ara.2014 13:53:21 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Hastane generated by hbm2java
 */
public class Hastane  implements java.io.Serializable {


     private int hid;
     private String ad;
     private String il;
     private String ilce;
     private String konum;
     private Set<Doktor> doktors = new HashSet<Doktor>(0);
     private Set<Hbirim> hbirims = new HashSet<Hbirim>(0);

    public Hastane() {
    }

	
    public Hastane(int hid) {
        this.hid = hid;
    }
    public Hastane(int hid, String ad, String il, String ilce, String konum, Set<Doktor> doktors, Set<Hbirim> hbirims) {
       this.hid = hid;
       this.ad = ad;
       this.il = il;
       this.ilce = ilce;
       this.konum = konum;
       this.doktors = doktors;
       this.hbirims = hbirims;
    }
   
    public int getHid() {
        return this.hid;
    }
    
    public void setHid(int hid) {
        this.hid = hid;
    }
    public String getAd() {
        return this.ad;
    }
    
    public void setAd(String ad) {
        this.ad = ad;
    }
    public String getIl() {
        return this.il;
    }
    
    public void setIl(String il) {
        this.il = il;
    }
    public String getIlce() {
        return this.ilce;
    }
    
    public void setIlce(String ilce) {
        this.ilce = ilce;
    }
    public String getKonum() {
        return this.konum;
    }
    
    public void setKonum(String konum) {
        this.konum = konum;
    }
    public Set<Doktor> getDoktors() {
        return this.doktors;
    }
    
    public void setDoktors(Set<Doktor> doktors) {
        this.doktors = doktors;
    }
    public Set<Hbirim> getHbirims() {
        return this.hbirims;
    }
    
    public void setHbirims(Set<Hbirim> hbirims) {
        this.hbirims = hbirims;
    }




}


