package com.pojos;
// Generated 01.Ara.2014 13:53:21 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Htanim generated by hbm2java
 */
public class Htanim  implements java.io.Serializable {


     private int htid;
     private String ad;
     private String tanim;
     private Set<Khastalik> khastaliks = new HashSet<Khastalik>(0);

    public Htanim() {
    }

	
    public Htanim(int htid) {
        this.htid = htid;
    }
    public Htanim(int htid, String ad, String tanim, Set<Khastalik> khastaliks) {
       this.htid = htid;
       this.ad = ad;
       this.tanim = tanim;
       this.khastaliks = khastaliks;
    }
   
    public int getHtid() {
        return this.htid;
    }
    
    public void setHtid(int htid) {
        this.htid = htid;
    }
    public String getAd() {
        return this.ad;
    }
    
    public void setAd(String ad) {
        this.ad = ad;
    }
    public String getTanim() {
        return this.tanim;
    }
    
    public void setTanim(String tanim) {
        this.tanim = tanim;
    }
    public Set<Khastalik> getKhastaliks() {
        return this.khastaliks;
    }
    
    public void setKhastaliks(Set<Khastalik> khastaliks) {
        this.khastaliks = khastaliks;
    }




}


