package com.pojos;
// Generated 01.Ara.2014 13:53:21 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * IlacBilgi generated by hbm2java
 */
public class IlacBilgi  implements java.io.Serializable {


     private int ibid;
     private Doz doz;
     private Ilac ilac;
     private Set<Recete> recetes = new HashSet<Recete>(0);

    public IlacBilgi() {
    }

	
    public IlacBilgi(int ibid) {
        this.ibid = ibid;
    }
    public IlacBilgi(int ibid, Doz doz, Ilac ilac, Set<Recete> recetes) {
       this.ibid = ibid;
       this.doz = doz;
       this.ilac = ilac;
       this.recetes = recetes;
    }
   
    public int getIbid() {
        return this.ibid;
    }
    
    public void setIbid(int ibid) {
        this.ibid = ibid;
    }
    public Doz getDoz() {
        return this.doz;
    }
    
    public void setDoz(Doz doz) {
        this.doz = doz;
    }
    public Ilac getIlac() {
        return this.ilac;
    }
    
    public void setIlac(Ilac ilac) {
        this.ilac = ilac;
    }
    public Set<Recete> getRecetes() {
        return this.recetes;
    }
    
    public void setRecetes(Set<Recete> recetes) {
        this.recetes = recetes;
    }




}


