package com.pojos;
// Generated 01.Ara.2014 13:53:21 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Ilac generated by hbm2java
 */
public class Ilac  implements java.io.Serializable {


     private int iid;
     private String iad;
     private String sgk;
     private String etkenmadde;
     private String kullanim;
     private String aciklama;
     private Set<IlacBilgi> ilacBilgis = new HashSet<IlacBilgi>(0);

    public Ilac() {
    }

	
    public Ilac(int iid) {
        this.iid = iid;
    }
    public Ilac(int iid, String iad, String sgk, String etkenmadde, String kullanim, String aciklama, Set<IlacBilgi> ilacBilgis) {
       this.iid = iid;
       this.iad = iad;
       this.sgk = sgk;
       this.etkenmadde = etkenmadde;
       this.kullanim = kullanim;
       this.aciklama = aciklama;
       this.ilacBilgis = ilacBilgis;
    }
   
    public int getIid() {
        return this.iid;
    }
    
    public void setIid(int iid) {
        this.iid = iid;
    }
    public String getIad() {
        return this.iad;
    }
    
    public void setIad(String iad) {
        this.iad = iad;
    }
    public String getSgk() {
        return this.sgk;
    }
    
    public void setSgk(String sgk) {
        this.sgk = sgk;
    }
    public String getEtkenmadde() {
        return this.etkenmadde;
    }
    
    public void setEtkenmadde(String etkenmadde) {
        this.etkenmadde = etkenmadde;
    }
    public String getKullanim() {
        return this.kullanim;
    }
    
    public void setKullanim(String kullanim) {
        this.kullanim = kullanim;
    }
    public String getAciklama() {
        return this.aciklama;
    }
    
    public void setAciklama(String aciklama) {
        this.aciklama = aciklama;
    }
    public Set<IlacBilgi> getIlacBilgis() {
        return this.ilacBilgis;
    }
    
    public void setIlacBilgis(Set<IlacBilgi> ilacBilgis) {
        this.ilacBilgis = ilacBilgis;
    }




}


