package com.pojos;
// Generated 01.Ara.2014 13:53:21 by Hibernate Tools 4.3.1



/**
 * Khastalik generated by hbm2java
 */
public class Khastalik  implements java.io.Serializable {


     private KhastalikId id;
     private Birey birey;
     private Htanim htanim;

    public Khastalik() {
    }

	
    public Khastalik(KhastalikId id) {
        this.id = id;
    }
    public Khastalik(KhastalikId id, Birey birey, Htanim htanim) {
       this.id = id;
       this.birey = birey;
       this.htanim = htanim;
    }
   
    public KhastalikId getId() {
        return this.id;
    }
    
    public void setId(KhastalikId id) {
        this.id = id;
    }
    public Birey getBirey() {
        return this.birey;
    }
    
    public void setBirey(Birey birey) {
        this.birey = birey;
    }
    public Htanim getHtanim() {
        return this.htanim;
    }
    
    public void setHtanim(Htanim htanim) {
        this.htanim = htanim;
    }




}


