package com.pojos;
// Generated 01.Ara.2014 13:53:21 by Hibernate Tools 4.3.1



/**
 * KhastalikId generated by hbm2java
 */
public class KhastalikId  implements java.io.Serializable {


     private String tcno;
     private Integer htid;

    public KhastalikId() {
    }

    public KhastalikId(String tcno, Integer htid) {
       this.tcno = tcno;
       this.htid = htid;
    }
   
    public String getTcno() {
        return this.tcno;
    }
    
    public void setTcno(String tcno) {
        this.tcno = tcno;
    }
    public Integer getHtid() {
        return this.htid;
    }
    
    public void setHtid(Integer htid) {
        this.htid = htid;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof KhastalikId) ) return false;
		 KhastalikId castOther = ( KhastalikId ) other; 
         
		 return ( (this.getTcno()==castOther.getTcno()) || ( this.getTcno()!=null && castOther.getTcno()!=null && this.getTcno().equals(castOther.getTcno()) ) )
 && ( (this.getHtid()==castOther.getHtid()) || ( this.getHtid()!=null && castOther.getHtid()!=null && this.getHtid().equals(castOther.getHtid()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getTcno() == null ? 0 : this.getTcno().hashCode() );
         result = 37 * result + ( getHtid() == null ? 0 : this.getHtid().hashCode() );
         return result;
   }   


}


